// <auto-generated />
using System;
using System.Collections.Generic;
using DriveLog.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DriveLog.Infrastructure.Migrations
{
    [DbContext(typeof(DriveLogDbContext))]
    [Migration("20260529211615_UpdateDomainLayer")]
    partial class UpdateDomainLayer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DriveLog.Domain.Entities.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("cars", null, t =>
                        {
                            t.HasCheckConstraint("CK_car_number_positive", "\"Number\" > 0");
                        });
                });

            modelBuilder.Entity("DriveLog.Domain.Entities.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Name", "DriveLog.Domain.Entities.Driver.Name#DriverName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");
                        });

                    b.HasKey("Id");

                    b.ToTable("drivers", null, t =>
                        {
                            t.HasCheckConstraint("CK_driver_number_positive", "\"Number\" > 0");
                        });
                });

            modelBuilder.Entity("DriveLog.Domain.Entities.Race", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActualEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ActualStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.ToTable("races", (string)null);
                });

            modelBuilder.Entity("DriveLog.Domain.Entities.RaceEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("DriverId");

                    b.HasIndex("RaceId", "CarId")
                        .IsUnique()
                        .HasDatabaseName("IX_unique_race_car");

                    b.HasIndex("RaceId", "DriverId")
                        .IsUnique()
                        .HasDatabaseName("IX_unique_race_driver");

                    b.ToTable("race_entries", (string)null);
                });

            modelBuilder.Entity("DriveLog.Domain.Entities.RaceLap", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<Guid>("RaceEntryId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("RaceEntryId", "Id")
                        .IsUnique()
                        .HasDatabaseName("PK_race_entry_lap_number");

                    b.ToTable("race_laps", null, t =>
                        {
                            t.HasCheckConstraint("CK_lap_number_positive", "\"Id\" > 0");
                        });
                });

            modelBuilder.Entity("DriveLog.Domain.Entities.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tracks", (string)null);
                });

            modelBuilder.Entity("DriveLog.Domain.Entities.Race", b =>
                {
                    b.HasOne("DriveLog.Domain.Entities.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DriveLog.Domain.Entities.RaceEntry", b =>
                {
                    b.HasOne("DriveLog.Domain.Entities.Car", null)
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DriveLog.Domain.Entities.Driver", null)
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DriveLog.Domain.Entities.Race", null)
                        .WithMany("Entries")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DriveLog.Domain.Entities.RaceLap", b =>
                {
                    b.HasOne("DriveLog.Domain.Entities.RaceEntry", null)
                        .WithMany("Laps")
                        .HasForeignKey("RaceEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DriveLog.Domain.Entities.Race", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("DriveLog.Domain.Entities.RaceEntry", b =>
                {
                    b.Navigation("Laps");
                });
#pragma warning restore 612, 618
        }
    }
}
