// <auto-generated />
using System;
using System.Collections.Generic;
using DriveLog.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DriveLog.Infrastructure.Migrations
{
    [DbContext(typeof(DriveLogDbContext))]
    [Migration("20260503190215_UpdateRacingNumber")]
    partial class UpdateRacingNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DriveLog.Domain.Entities.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Number", "DriveLog.Domain.Entities.Car.Number#RacingNumber", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Value")
                                .HasColumnType("integer");
                        });

                    b.HasKey("Id");

                    b.ToTable("Cars", null, t =>
                        {
                            t.HasCheckConstraint("CK_Car_Number", "\"Number\" > 0");
                        });
                });

            modelBuilder.Entity("DriveLog.Domain.Entities.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "FullName", "DriveLog.Domain.Entities.Driver.FullName#FullName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Number", "DriveLog.Domain.Entities.Driver.Number#RacingNumber", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Value")
                                .HasColumnType("integer");
                        });

                    b.HasKey("Id");

                    b.ToTable("Drivers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Driver_Number", "\"Number\" > 0");
                        });
                });

            modelBuilder.Entity("DriveLog.Domain.Entities.Race", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("DriveLog.Domain.Entities.RaceLap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<int>("LapNumber")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("LapTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("RaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("DriverId");

                    b.HasIndex("RaceId");

                    b.ToTable("RaceLaps");
                });

            modelBuilder.Entity("DriveLog.Domain.Entities.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("DriveLog.Domain.Entities.Race", b =>
                {
                    b.HasOne("DriveLog.Domain.Entities.Track", "Track")
                        .WithMany("Races")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("DriveLog.Domain.Entities.RaceLap", b =>
                {
                    b.HasOne("DriveLog.Domain.Entities.Car", "Car")
                        .WithMany("RaceLaps")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DriveLog.Domain.Entities.Driver", "Driver")
                        .WithMany("RaceLaps")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DriveLog.Domain.Entities.Race", "Race")
                        .WithMany("RaceLaps")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Driver");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("DriveLog.Domain.Entities.Car", b =>
                {
                    b.Navigation("RaceLaps");
                });

            modelBuilder.Entity("DriveLog.Domain.Entities.Driver", b =>
                {
                    b.Navigation("RaceLaps");
                });

            modelBuilder.Entity("DriveLog.Domain.Entities.Race", b =>
                {
                    b.Navigation("RaceLaps");
                });

            modelBuilder.Entity("DriveLog.Domain.Entities.Track", b =>
                {
                    b.Navigation("Races");
                });
#pragma warning restore 612, 618
        }
    }
}
